name: GitHub Actions Demo
on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: cd ./learnjsvite
      - run: npm install
      - run: npm run build
